apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: mongodb
spec:
  selector:
    app: mongo
  clusterIP: None
  ports:
    - protocol: TCP
      port: 27017  # The port on the service
      targetPort: 27017  # The port on the pods targeted by the service
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: mongo
  namespace: mongodb
spec:
  serviceName: mongo
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - mongo
              topologyKey: kubernetes.io/hostname
      containers:
      - name: mongo
        #image: mongo
        #imagePullPolicy: Never
        image: docker.io/library/mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
          - name: mongo-persistent-storage
            mountPath: /data/db
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo_username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo_password
  volumeClaimTemplates:
    - metadata:
        name: mongo-persistent-storage
        labels:
          app: mongo
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 5Gi
